---
title: "reimplementation of circle plot"
output: html_document
---

# Read in data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)

pgrdata <- read_csv(here::here("Data/RealData_20210302-0945.csv"))
surveyindex <- read_csv(here("Data/SurveyIndex.csv"))
targetnumbers <- read_csv(here("Data/TargetNumbers.csv"))

```

## Format the basic data
```{r}
# rename columns and drop invalid data
valid_data <- pgrdata %>% 
  slice(3:n()) %>% 
  select(-c(DistributionChannel, UserLanguage)) %>% 
  # replace column names w the corresponding one in the survey index
  rename_with(~ surveyindex %>% filter(QuestionCode == .) %>% pull(VariableName)) %>% 
  filter(!is.na(Consent) & !is.na(DivCol) & !is.na(Role))

# grab the departments
departments <- valid_data %>% 
  select(ResponseId, contains("Dept")) %>%
  pivot_longer(cols = -ResponseId) %>% 
  filter(!is.na(value)) %>% 
  select(-name) %>% 
  rename(Dept = value)

# wrangle the data
wrangled_data <- valid_data %>% 
  mutate(Consent = if_else(Consent == "I consent to participating in the survey and to processing of the information I provide as outlined above.", TRUE, FALSE)) %>% 
  # add division
  mutate(Div = case_when(
    DivCol == "Social Sciences Division" ~ "SSD",
    DivCol == "Humanities Division" ~ "Hum",
    DivCol == "Department for Continuing Education" ~ "ContEd",
    DivCol == "Mathematical, Physical, and Life Sciences Division" ~ "MPLS",
    DivCol == "Medical Sciences Division" ~ "MSD",
    DivCol == "Gardens, Libraries and Museums" ~ "GLAM"
  )) %>% 
  # add the departments
  select(-starts_with("Dept")) %>% 
  left_join(departments) %>% 
  mutate(StudentStaff = if_else(Role == "Student on a postgraduate research programme", "Student", "Staff")) %>% # add student status
  mutate(Duration = parse_number(Duration)) %>% # pase duration as number
  select(-c(DivCol, ColDiv)) # drop unused columns

```

## Create summarised data set for awareness
```{r}
count_awareness <- wrangled_data %>% 
  filter(StudentStaff == "Student") %>% 
  select(Div, starts_with("Awareness")) %>% 
  pivot_longer(-Div) %>% 
  rename(aspect = name, awareness_level = value) %>% 
  mutate(aspect = str_remove(aspect, "Awareness_"),
         aspect = case_when(
           aspect == "Code" ~ "Open Code",
           aspect == "Data" ~ "Open Data",
           aspect == "Materials" ~ "Open Materials", 
           aspect == "OA" ~ "Open Access",
           aspect == "Preprint" ~ "Preprint",
           aspect == "Prereg" ~ "Preregistration",
           aspect == "RegRep" ~ "Registered Report"
         ),
         aspect = factor(aspect)) %>% 
  count(Div, aspect, awareness_level) %>% 
  group_by(Div, aspect) %>% 
  mutate(ptc = (n/sum(n) * 100)) %>% 
  arrange(Div, aspect, awareness_level)
  

```



# Visualise it
## Recreate the circular plot
Based on this: https://www.r-graph-gallery.com/297-circular-barplot-with-groups.html




```{r}
# library
library(tidyverse)
 
# Create dataset
data <- data.frame(
  individual=paste( "Mister ", seq(1,60), sep=""),
  group=c( rep('A', 10), rep('B', 30), rep('C', 14), rep('D', 6)) ,
  value=sample( seq(10,100), 60, replace=T)
)
 
# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 3
to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$group), ncol(data)) )
colnames(to_add) <- colnames(data)
to_add$group <- rep(levels(data$group), each=empty_bar)
data <- rbind(data, to_add)
data <- data %>% arrange(group)
data$id <- seq(1, nrow(data))
 
# Get the name and the y position of each label
label_data <- data
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data <- data %>% 
  group_by(group) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))
 
# prepare a data frame for grid (scales)
grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]
 
# Make the plot
p <- ggplot(data, aes(x=as.factor(id), y=value, fill=group)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  
  geom_bar(aes(x=as.factor(id), y=value, fill=group), stat="identity", alpha=0.5) +
  
  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
  # Add text showing the value of each 100/75/50/25 lines
  annotate("text", x = rep(max(data$id),4), y = c(20, 40, 60, 80), label = c("20", "40", "60", "80") , color="grey", size=3 , angle=0, fontface="bold", hjust=1) +
  
  geom_bar(aes(x=as.factor(id), y=value, fill=group), stat="identity", alpha=0.5) +
  ylim(-100,120) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  coord_polar() + 
  geom_text(data=label_data, aes(x=id, y=value+10, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) +
  
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -18, label=group), hjust=c(1,1,0,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE)
 
p
```




```{r pressure, echo=FALSE}
circular_plot_function <- function(data, Question, answers, title_plot, answers_colors) {

  name_data_argument <- deparse(substitute(data)) # get the name of the dataset to apply if statement below
  
  data$LabelIndiv <- factor(data$LabelIndiv, levels = Question) # this will determine order of the bars
  
  # Set a number of 'empty bar' to add at the end of each Div
  empty_bar <- 2
  nObsType <- nlevels(data$Answer)
  to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$Div)*nObsType, ncol(data)) )
  colnames(to_add) <- colnames(data)
  to_add$Div <- rep(levels(data$Div), each=empty_bar*nObsType )
  data <- rbind(data, to_add)
  data <- data %>% arrange(Div, LabelIndiv) # this will determine order of the bars
  data$id <- rep( seq(1, nrow(data)/nObsType) , each=nObsType)
  rm(to_add)
  
  # Get the name and the y position of each label
  label_data <- data %>% group_by(id, Indiv) %>% summarize(tot=sum(perc, na.rm=TRUE)) # here all at 100% to plot percents and not counts
  number_of_bar <- nrow(label_data)
  angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
  label_data$hjust <- ifelse(angle < -90, 1, 0)
  label_data$angle <- ifelse(angle < -90, angle+180, angle)
  label_data$LabelIndiv <- sapply(strsplit(as.character(label_data$Indiv),"\\_"), `[`, 2)
  
  # prepare a data frame for base lines
  base_data <- data %>% 
    group_by(Div) %>% 
    summarize(start=min(id), end=max(id) - empty_bar) %>% 
    rowwise() %>% 
    mutate(title=mean(c(start, end)))
  
if (name_data_argument == 'pgrdata_Awareness'){
base_data$title[base_data$Div == 'SSD'] <- 39} #for awareness plot

if (name_data_argument == 'pgrdata_Training'){
base_data$title[base_data$Div == 'SSD'] <- 51} #for training plot
  
  
  # prepare a data frame for grid (scales)
  grid_data <- base_data
  grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
  grid_data$start <- grid_data$start - 1
  grid_data <- grid_data[-1,]
  
  
  
  
  
  ## Make the plot
  pgrdata_Support_plot <- ggplot(data) +     
    
    ### Add the stacked bar
    geom_bar(aes(x=as.factor(id), y=perc, fill=factor(Answer, level = answers)), stat="identity", alpha=0.5) +
    
    ### Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
    geom_segment(data=grid_data, aes(x = end, y = 0, xend = start, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) + 
    geom_segment(data=grid_data, aes(x = end, y = 25, xend = start, yend = 25), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = end, y = 50, xend = start, yend = 50), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = end, y = 75, xend = start, yend = 75), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = number_of_bar-1, y = 100, xend = number_of_bar, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = number_of_bar-1, y = 75, xend = number_of_bar, yend = 75), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = number_of_bar-1, y = 50, xend = number_of_bar, yend = 50), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = number_of_bar-1, y = 25, xend = number_of_bar, yend = 25), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = number_of_bar-1, y = 0, xend = number_of_bar, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    
    ### Add text showing the value of each lines max(data$id-0.1)
    ggplot2::annotate("text", x = rep(number_of_bar-0.5,5), y = c(0, 25, 50, 75, 100), label = c("0%", "25%", "50%", "75%", "100%") , color="dimgrey", size=3 , angle=0, fontface="bold", hjust=c(0.5,0.5,0.5,0.5,0.5), vjust = -0.2) +
    
    scale_fill_manual(values = rev(answers_colors), # https://www.datanovia.com/en/blog/top-r-color-palettes-to-know-for-great-data-visualization/
                      breaks = answers, 
                      labels = answers, 
                      drop = FALSE)+

    scale_x_discrete(expand = c(0, 0)) +
    ylim(-70,150) +
    theme_minimal() +
    theme(
      legend.position = "right",
      legend.text=element_text(size=13),
      legend.title=element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      panel.grid = element_blank(),
      panel.border=element_blank(), axis.ticks.length = unit(0, "mm")
    ) +
    
   # guides(fill=guide_legend(nrow=2,byrow=FALSE))+
    
    coord_polar() +
    
    ### Add labels on top of each bar
    geom_text(data=label_data, aes(x=id, y=105, label=LabelIndiv, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=4.3, angle= label_data$angle, inherit.aes = FALSE ) + 
    
    ### Add base line information
    geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
    geom_text(data=base_data, aes(x = title, y = -20, label=Div), hjust=c(1,1,0.5,0, 0), colour = "black", alpha=0.8,  size=4, fontface="bold", inherit.aes = FALSE) + 
    
    ### Add title in the middle
    ggplot2::annotate("text", x = 0, y = -60, label = title_plot , color="black", size=5.5 , angle=0, fontface="bold", hjust=0.5) 
  
  
}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
